### ISSUE TITLE
Basic run - 🐛 

### ISSUE THREAD

**Issue by omesser** [chanchalr/parsemetrics#5]
Hey @chanchalr 

trying to run with a very basic scenario (just following the README) - I've created a simple (`run.py`) with contents:

```py
#!/usr/bin/env python
import iterative_metrics


def main():
    parser = iterative_metrics.metric_parser("./config.yaml")
    parser.parse_repo('metrics-demo', 'metrics.json')

    first_commit = parser.fetch_repo_data(count=1)

    print(first_commit)
    # second_commit = parser.fetch_repo_data(commit_id=first_commit[0]["commit_id"],count=1)
    # print(second_commit)
    # first_again = parser.fetch_repo_data(commit_id=second_commit[0]["commit_id"],count=1,direction="back")


if __name__ == '__main__':
    main()

```

and running it, it Immediate failed for me with:

```bash
/Users/oded/iterative/misc_workspace/studio_tasks/parsemetrics_chanchal/venv/bin/python /Users/oded/iterative/misc_workspace/studio_tasks/parsemetrics_chanchal/run.py
Traceback (most recent call last):
  File "/Users/oded/iterative/misc_workspace/studio_tasks/parsemetrics_chanchal/run.py", line 18, in <module>
    main()
  File "/Users/oded/iterative/misc_workspace/studio_tasks/parsemetrics_chanchal/run.py", line 7, in main
    parser.parse_repo('metrics-demo', 'metrics.json')
  File "/Users/oded/iterative/misc_workspace/studio_tasks/parsemetrics_chanchal/iterative_metrics/__init__.py", line 20, in parse_repo
    self.db.add_commits(commit_group)
TypeError: postgres_db.add_commits() missing 2 required positional arguments: 'metrics_path' and 'commits'
```

I think it's just a simple bug of missing passing some arguments here:

https://github.com/chanchalr/parsemetrics/blob/4a9b24d35a1d97045c5c4cf3790a25afff2a57fe/iterative_metrics/__init__.py#L20

Should be:
```py
self.db.add_commits(repo_path, metrics_file, commit_group)
```
IMO

Am I correct?
Also, I just want to make sure I'm not missing anything and the repo is indeed ready for review

**Comment by chanchalr** [comment]
Yes you are right @omesser  default params were missing there. This was because of an optimisation i did to send bulk inserts and missed testing with large repo after that. I have fixed the issue and have added test cases for that
